# Exception Handling

Error handling - When we get an error instead of showing a random error message we will show user-defined error message

In [1]:
a=5
print(b)

NameError: name 'b' is not defined

Error - When something in our code goes wrong we get error

1. Name Error
2. Value Error
3. Type Error
4. Zero Division Error

In [2]:
a=5
b='str'

a+b

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [4]:
int('three')

ValueError: invalid literal for int() with base 10: 'three'

In [5]:
a=5
b=0

a/b

ZeroDivisionError: division by zero

3 blocks

1. Try block - Where our code goes
2. Except block - Where we will expect errors and provide alternate actions
3. Finally block - Displays or does anything when we get/ do not error

In [8]:
try:
    int('three')
    
except ZeroDivisionError:
    print('Check the denominator')
except ValueError:
    print('Check the value')
except NameError:
    print('Check the variable name')
except:
    print('Some error')

Check the value


In [10]:
try:
    int('3')
    
except ZeroDivisionError:
    print('Check the denominator')
except ValueError:
    print('Check the value')
except NameError:
    print('Check the variable name')
except:
    print('Some error')
finally:
    print('Execution over')

Execution over


# Basics of Data Science



1. Numpy - Array that can be used for mathematical calculations
2. Pandas - Data Analysis

In [13]:
import numpy as np

In [14]:
arr=np.array([1,2,3,4])

arr

array([1, 2, 3, 4])

In [15]:
print(type(arr))

<class 'numpy.ndarray'>


In [18]:
arr.ndim

1

In [19]:
arr.shape

(4,)

In [20]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr1.shape

(3, 3)

In [23]:
arr.size

4

In [24]:
arr1.size

9

In [25]:
2*arr

array([2, 4, 6, 8])

In [26]:
arr+2

array([3, 4, 5, 6])

In [28]:
arr2=np.array(['Danton Jesuraja','Shivkrish'])

arr2

array(['Danton Jesuraja', 'Shivkrish'], dtype='<U15')

In [30]:
arr3=np.linspace(1,100,10)

arr3

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [31]:
for i in arr3:
    print(i)

1.0
12.0
23.0
34.0
45.0
56.0
67.0
78.0
89.0
100.0


In [34]:
arr3[0:3]

array([ 1., 12., 23.])

## Pandas

1. Series - 1D
2. Dataframe - 2D

In [35]:
import pandas as pd

In [36]:
df=pd.read_csv("C:/Users/DELL/Desktop/data.csv")

df

Name   Age
0    Danton  27.0
1     Nalin  17.0
2  Jesuraja   NaN

In [37]:
ser1=df['Name']

ser1

0      Danton
1       Nalin
2    Jesuraja
Name: Name, dtype: object

In [38]:
print(type(ser1))

<class 'pandas.core.series.Series'>


## Loading data from dict

In [42]:
dict1={'Name':['Danton','Shivkrish'],'Age':[27,18]}

df=pd.DataFrame(dict1,index=['One','Two'])

In [43]:
df

Name  Age
One     Danton   27
Two  Shivkrish   18

## Locating values inside Dataframe

In [45]:
df.loc['One','Name']='Jesuraja'

In [46]:
df

Name  Age
One   Jesuraja   27
Two  Shivkrish   18

In [48]:
df.iloc[0,0]='Danton'

In [49]:
df

Name  Age
One     Danton   27
Two  Shivkrish   18